/**
 * ParallelQuoteApprovalController_test
 *
 * Description:
 *   Test class for ParallelQuoteApprovalController
 *
 * Revision History:
 *
 *   Kyle Vermeer         1/7/2014        Initial Creation
 *   Kyle Vermeer         6/6/2014        Commented out by KV - deprecated
 */

@isTest
private class ParallelQuoteApprovalController_test {
    
    /*
    @isTest static void testFull() {
        // Create Sample User
        Id userId = TestDataFactory_hlpr.createUser('Major','NATAM','Kyle V','blahblah@test.st');

        // Create Sample Opp
        Opportunity opp = new Opportunity(OwnerId = userId, Name = 'Major - NATAM Opp', StageName = 'Recieved / Prospecting' , 
                                          CloseDate = Date.today().addDays(1));
        insert opp;

        // Create Sample Quote
        Quote testQuote = new Quote(OpportunityId=opp.Id, Name = 'Major - NATAM Quote', pricebook2Id = '01s60000000APgk',
                                    Product_Tier__c='Business');
        insert testQuote;

        ApexPages.currentPage().getParameters().put('id', testQuote.Id);
        ParallelQuoteApprovalController controller = new ParallelQuoteApprovalController();
        controller.launchQuoteApprovals();
    }
    */
    
}